'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'
const MODULES=[['CORE_HR','Core HR'],['ATTENDANCE','Attendance'],['LEAVE','Leave'],['PAYROLL','Payroll'],['RECRUITMENT','Recruitment'],['ONBOARDING','Onboarding'],['PERFORMANCE','Performance'],['EXPENSES','Expenses'],['REPORTS','Reports']] as const
const configs:any={
 'Core HR':{table:'employees',title:'Employees',fields:[['employee_code','Employee Code','text'],['first_name','First Name','text'],['last_name','Last Name','text'],['work_email','Work Email','email'],['phone','Phone','text'],['date_of_joining','Joining Date','date'],['employment_type','Employment Type','text']],select:'employee_code,first_name,last_name,work_email,phone,date_of_joining,employment_status,employment_type,department_id,designation_id'},
 'Attendance':{table:'attendance_daily',title:'Daily Attendance',fields:[['attendance_date','Date','date'],['status','Status','text'],['worked_minutes','Worked Minutes','number'],['source','Source','text']],select:'id,attendance_date,employee_id,first_in,last_out,worked_minutes,status,source'},
 'Leave':{table:'leave_requests',title:'Leave Requests',fields:[['start_date','Start Date','date'],['end_date','End Date','date'],['days','Days','number'],['reason','Reason','text']],select:'id,employee_id,leave_type_id,start_date,end_date,days,reason,status'},
 'Payroll':{table:'payroll_runs',title:'Payroll Runs',fields:[['payroll_month','Payroll Month','date'],['status','Status','text']],select:'id,payroll_month,status,processed_at,approved_at'},
 'Recruitment':{table:'job_requisitions',title:'Job Requisitions',fields:[['title','Job Title','text'],['positions','Positions','number'],['employment_type','Employment Type','text'],['description','Description','text']],select:'id,title,positions,employment_type,status,description,created_at'},
 'Onboarding':{table:'onboarding_tasks',title:'Onboarding Tasks',fields:[['title','Task','text'],['due_date','Due Date','date'],['status','Status','text']],select:'id,employee_id,title,due_date,status,assigned_to'},
 'Performance':{table:'performance_cycles',title:'Performance Cycles',fields:[['name','Cycle Name','text'],['start_date','Start Date','date'],['end_date','End Date','date'],['status','Status','text']],select:'id,name,start_date,end_date,status'},
 'Expenses':{table:'expense_claims',title:'Expense Claims',fields:[['expense_date','Expense Date','date'],['amount','Amount','number'],['description','Description','text'],['status','Status','text']],select:'id,employee_id,category_id,expense_date,amount,description,status'},
 'Reports':{table:'employees',title:'Management Reports',fields:[],select:'id'}
}
export default function HRMS(){
 const [user,setUser]=useState<any>(null),[org,setOrg]=useState<any>(null),[enabled,setEnabled]=useState<string[]>([]),[tab,setTab]=useState('Dashboard'),[rows,setRows]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[showForm,setShowForm]=useState(false),[form,setForm]=useState<any>({}),[detail,setDetail]=useState<any>(null)
 const visible=MODULES.filter(x=>enabled.includes(x[0])); const cfg=configs[tab]
 async function loadModule(name=tab){setErr('');if(name==='Dashboard')return; if(name==='Reports')return;const c=configs[name];if(!c)return;setBusy(true);const q=await supabase.from(c.table).select(c.select).eq('organization_id',org.id).order('created_at',{ascending:false}).limit(100);if(q.error)setErr(q.error.message);else setRows(q.data||[]);setBusy(false)}
 async function load(){const u=await supabase.auth.getUser();if(!u.data.user){location.href='/login';return}const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error||aal.data.currentLevel!=='aal2'){location.href='/mfa-setup?next=/hrms';return}setUser(u.data.user);const m=await supabase.from('organization_members').select('organization_id,employee_id').eq('user_id',u.data.user.id).eq('status','ACTIVE').maybeSingle();if(m.error||!m.data){setErr('No customer organization is linked to this account.');return}const o=await supabase.from('organizations').select('id,name,code,status,timezone,currency').eq('id',m.data.organization_id).single();if(o.error){setErr(o.error.message);return}setOrg(o.data);const om=await supabase.from('organization_modules').select('module_code').eq('organization_id',m.data.organization_id).eq('enabled',true);setEnabled((om.data||[]).map((x:any)=>x.module_code));const e=await supabase.from('employees').select('id,employee_code,first_name,last_name,work_email,employment_status,employment_type').eq('organization_id',m.data.organization_id).order('created_at',{ascending:false});setEmployees(e.data||[])}
 useEffect(()=>{load()},[]);useEffect(()=>{if(org&&tab!=='Dashboard')loadModule(tab)},[tab,org])
 async function save(){if(!org||!cfg||tab==='Reports')return;setBusy(true);setErr('');let payload={...form,organization_id:org.id};if(tab==='Core HR'){payload.employment_status=payload.employment_status||'ACTIVE';payload.employment_type=payload.employment_type||'FULL_TIME'}const r=await supabase.from(cfg.table).insert(payload).select().single();if(r.error)setErr(r.error.message);else{setShowForm(false);setForm({});await loadModule(tab);await load()};setBusy(false)}
 async function updateStatus(id:string,status:string){if(!cfg)return;const r=await supabase.from(cfg.table).update({status}).eq('id',id).eq('organization_id',org.id);if(r.error)setErr(r.error.message);else loadModule(tab)}
 async function webCheck(type:'IN'|'OUT'){const me=employees.find(e=>e.id===detail?.employee_id)||employees[0];if(!me){setErr('No employee found');return}const r=await supabase.from('attendance_events').insert({organization_id:org.id,employee_id:me.id,event_type:type,source:'WEB',occurred_at:new Date().toISOString(),verification_status:'VERIFIED'});if(r.error)setErr(r.error.message);else{setDetail({employee_id:me.id});alert(`${type==='IN'?'Check-in':'Check-out'} recorded for ${me.first_name} ${me.last_name||''}`);if(tab==='Attendance')loadModule('Attendance')}}
 async function logout(){await supabase.auth.signOut();location.href='/login'}
 return <main className="app-shell"><aside className="app-side"><img src="/humanest-logo.png" className="side-logo"/><div className="org">{org?.name||'Loading…'}</div><nav><button className={tab==='Dashboard'?'on':''} onClick={()=>setTab('Dashboard')}>Dashboard</button>{visible.map(m=><button key={m[0]} className={tab===m[1]?'on':''} onClick={()=>setTab(m[1])}>{m[1]}</button>)}<button className={tab==='My Profile'?'on':''} onClick={()=>setTab('My Profile')}>My Profile</button><button className={tab==='Settings'?'on':''} onClick={()=>setTab('Settings')}>Settings</button></nav><button className="signout" onClick={logout}>Sign out</button></aside><section className="app-content"><header><div><div className="eyebrow left">HUMANEST HRMS</div><h1>{tab}</h1></div><div className="userpill">{user?.email}</div></header>{err&&<div className="error top-error">{err}</div>}{tab==='Dashboard'&&<Dashboard org={org} employees={employees} visible={visible} setTab={setTab}/>} {tab==='My Profile'&&<Profile user={user} org={org}/>} {tab==='Settings'&&<OrgSettings org={org}/>} {tab==='Reports'&&<Reports org={org} employees={employees}/>} {tab==='Attendance'&&<Attendance rows={rows} employees={employees} check={webCheck} setDetail={setDetail}/>} {tab==='Leave'&&<Leave rows={rows} employees={employees} onStatus={updateStatus} showForm={showForm} setShowForm={setShowForm} form={form} setForm={setForm} save={save} busy={busy}/>} {tab!=='Dashboard'&&tab!=='My Profile'&&tab!=='Settings'&&tab!=='Reports'&&tab!=='Attendance'&&tab!=='Leave'&&<CrudModule name={tab} cfg={cfg} rows={rows} showForm={showForm} setShowForm={setShowForm} form={form} setForm={setForm} save={save} busy={busy} onStatus={updateStatus}/>} </section></main>
}
function Dashboard({org,employees,visible,setTab}:{org:any,employees:any[],visible:any[],setTab:any}){return <><div className="welcome"><div><h2>Welcome to HumaNest</h2><p className="muted">Your People. Your Process.</p></div><span className={'status '+(org?.status||'').toLowerCase()}>{org?.status}</span></div><div className="stats"><Stat label="Employees" value={employees.length}/><Stat label="Enabled modules" value={visible.length}/><Stat label="Organization" value={org?.code||'—'}/><Stat label="Currency" value={org?.currency||'INR'}/></div><div className="module-cards">{visible.map(m=><button className="module-card" key={m[0]} onClick={()=>setTab(m[1])}><span>{icon(m[0])}</span><b>{m[1]}</b><small>Open workspace →</small></button>)}</div><div className="grid-2"><div className="card"><div className="cardhead"><h2>Employees</h2><button onClick={()=>setTab('Core HR')}>Manage →</button></div><table><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Status</th></tr></thead><tbody>{employees.slice(0,6).map(e=><tr key={e.id}><td>{e.employee_code}</td><td>{e.first_name} {e.last_name||''}</td><td>{e.work_email}</td><td><Badge s={e.employment_status}/></td></tr>)}</tbody></table></div><div className="card"><h2>Quick actions</h2><div className="quick-grid"><button onClick={()=>setTab('Core HR')}>+ Add Employee</button><button onClick={()=>setTab('Attendance')}>Record Attendance</button><button onClick={()=>setTab('Leave')}>Apply Leave</button><button onClick={()=>setTab('Expenses')}>Submit Expense</button></div></div></div></>}
function CrudModule({name,cfg,rows,showForm,setShowForm,form,setForm,save,busy,onStatus}:{name:string,cfg:any,rows:any[],showForm:boolean,setShowForm:any,form:any,setForm:any,save:any,busy:boolean,onStatus:any}){return <div className="card"><div className="cardhead"><div><h2>{cfg.title}</h2><p className="muted">{name} workspace · live database</p></div><button className="gradient" onClick={()=>setShowForm(!showForm)}>{showForm?'Close':`+ Add ${name==='Core HR'?'Employee':cfg.title.replace(/s$/,'')}`}</button></div>{showForm&&<Form fields={cfg.fields} form={form} setForm={setForm} save={save} busy={busy}/>}<div className="tablewrap"><table><thead><tr>{Object.keys(rows[0]||{}).filter(k=>k!=='id').slice(0,8).map(k=><th key={k}>{label(k)}</th>)}<th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{Object.keys(r).filter(k=>k!=='id').slice(0,8).map(k=><td key={k}>{typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</td>)}<td>{r.status&&<select value={r.status} onChange={e=>onStatus(r.id,e.target.value)}><option>{r.status}</option><option>ACTIVE</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>COMPLETED</option><option>CANCELLED</option></select>}</td></tr>)}{!rows.length&&<Empty/>}</tbody></table></div></div>}
function Attendance({rows,employees,check,setDetail}:any){return <><div className="stats"><Stat label="Today records" value={rows.length}/><Stat label="Employees" value={employees.length}/><Stat label="Source" value="Web + Biometric"/><Stat label="MFA" value="Verified"/></div><div className="card"><div className="cardhead"><div><h2>Attendance capture</h2><p className="muted">Web check-in/out is available now; biometric adapters can post attendance events to the same engine.</p></div><div className="action-row"><select onChange={e=>setDetail({employee_id:e.target.value})}><option value="">Select employee</option>{employees.map((e:any)=><option value={e.id} key={e.id}>{e.first_name} {e.last_name||''}</option>)}</select><button onClick={()=>check('IN')}>Check In</button><button onClick={()=>check('OUT')}>Check Out</button></div></div><table><thead><tr><th>Date</th><th>Employee</th><th>First In</th><th>Last Out</th><th>Minutes</th><th>Status</th><th>Source</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{r.attendance_date}</td><td>{employees.find((e:any)=>e.id===r.employee_id)?.first_name||r.employee_id}</td><td>{r.first_in||'—'}</td><td>{r.last_out||'—'}</td><td>{r.worked_minutes}</td><td><Badge s={r.status}/></td><td>{r.source||'—'}</td></tr>)}{!rows.length&&<Empty/>}</tbody></table></div></>}
function Leave({rows,employees,onStatus,showForm,setShowForm,form,setForm,save,busy}:any){return <div className="card"><div className="cardhead"><div><h2>Leave management</h2><p className="muted">Employee → immediate manager → approve/reject.</p></div><button className="gradient" onClick={()=>setShowForm(!showForm)}>{showForm?'Close':'+ Apply Leave'}</button></div>{showForm&&<div className="form-grid"><label>Employee<select value={form.employee_id||''} onChange={e=>setForm({...form,employee_id:e.target.value})}><option value="">Select</option>{employees.map((e:any)=><option value={e.id} key={e.id}>{e.first_name} {e.last_name||''}</option>)}</select></label><Form fields={[["leave_type_id","Leave Type ID","text"],["start_date","Start Date","date"],["end_date","End Date","date"],["days","Days","number"],["reason","Reason","text"]]} form={form} setForm={setForm} save={save} busy={busy}/></div>}<table><thead><tr><th>Employee</th><th>Start</th><th>End</th><th>Days</th><th>Reason</th><th>Status</th><th>Decision</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{employees.find((e:any)=>e.id===r.employee_id)?.first_name||r.employee_id}</td><td>{r.start_date}</td><td>{r.end_date}</td><td>{r.days}</td><td>{r.reason||'—'}</td><td><Badge s={r.status}/></td><td><button onClick={()=>onStatus(r.id,'APPROVED')}>Approve</button> <button onClick={()=>onStatus(r.id,'REJECTED')}>Reject</button></td></tr>)}{!rows.length&&<Empty/>}</tbody></table></div>}
function Reports({org,employees}:any){return <><div className="stats"><Stat label="Headcount" value={employees.length}/><Stat label="Active" value={employees.filter((e:any)=>e.employment_status==='ACTIVE').length}/><Stat label="Full time" value={employees.filter((e:any)=>e.employment_type==='FULL_TIME').length}/><Stat label="Organization" value={org?.name}/></div><div className="grid-2"><div className="card"><h2>HR report</h2><p className="muted">Live employee summary.</p><table><thead><tr><th>Employee</th><th>Type</th><th>Status</th></tr></thead><tbody>{employees.map((e:any)=><tr key={e.id}><td>{e.first_name} {e.last_name||''}</td><td>{e.employment_type}</td><td>{e.employment_status}</td></tr>)}</tbody></table></div><div className="card"><h2>Available reports</h2><div className="control-list"><div><b>Employee Register</b><span>Current employee master data.</span></div><div><b>Attendance Summary</b><span>Daily attendance and working time.</span></div><div><b>Leave Register</b><span>Leave applications and decisions.</span></div><div><b>Payroll Register</b><span>Payroll runs and net pay.</span></div></div></div></div></>}
function Profile({user,org}:any){return <div className="grid-2"><div className="card"><h2>My Profile</h2><div className="setting"><span>Email</span><b>{user?.email}</b></div><div className="setting"><span>Organization</span><b>{org?.name}</b></div><div className="setting"><span>MFA</span><b>Authenticator enabled</b></div></div><div className="card"><h2>Security</h2><p className="muted">Manage your Authenticator devices from the MFA security page.</p><a className="gradient inline" href="/mfa-setup?next=/hrms">MFA Security →</a></div></div>}
function OrgSettings({org}:any){return <div className="grid-2"><div className="card"><h2>Organization settings</h2><div className="setting"><span>Organization</span><b>{org?.name}</b></div><div className="setting"><span>Code</span><b>{org?.code}</b></div><div className="setting"><span>Timezone</span><b>{org?.timezone}</b></div><div className="setting"><span>Currency</span><b>{org?.currency}</b></div></div><div className="card"><h2>Workspace security</h2><div className="control-list"><div><b>Mandatory MFA</b><span>Authenticator MFA is required for customer access.</span></div><div><b>Tenant isolation</b><span>All HRMS records are scoped to this organization.</span></div></div></div></div>}
function Form({fields,form,setForm,save,busy}:any){return <div className="form-grid">{fields.map(([key,name,type]:any)=><label key={key}>{name}<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="gradient" onClick={save} disabled={busy}>{busy?'Saving…':'Save record'}</button></div>}
function Stat({label,value}:{label:string,value:any}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
function Badge({s}:{s:string}){return <span className={'badge '+String(s||'').toLowerCase().replaceAll(' ','-')}>{s}</span>}
function Empty(){return <tr><td colSpan={10} className="empty">No records yet.</td></tr>}
function label(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function icon(s:string){return ({CORE_HR:'◉',ATTENDANCE:'◷',LEAVE:'◫',PAYROLL:'₹',RECRUITMENT:'⌕',ONBOARDING:'✓',PERFORMANCE:'★',EXPENSES:'▣',REPORTS:'▥'} as any)[s]||'•'}
