'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
const modules=[['CORE_HR','Core HR'],['ATTENDANCE','Attendance'],['LEAVE','Leave'],['PAYROLL','Payroll'],['RECRUITMENT','Recruitment'],['ONBOARDING','Onboarding'],['PERFORMANCE','Performance'],['EXPENSES','Expenses'],['REPORTS','Reports']]
export default function HRMS(){
 const [user,setUser]=useState<any>(null),[org,setOrg]=useState<any>(null),[enabled,setEnabled]=useState<string[]>([]),[tab,setTab]=useState('Dashboard'),[emp,setEmp]=useState<any[]>([]),[err,setErr]=useState('')
 useEffect(()=>{(async()=>{const u=await supabase.auth.getUser();if(!u.data.user){location.href='/login';return}const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error||aal.data.currentLevel!=='aal2'){location.href='/mfa-setup?next=/hrms';return}setUser(u.data.user);const m=await supabase.from('organization_members').select('organization_id,employee_id').eq('user_id',u.data.user.id).eq('status','ACTIVE').maybeSingle();if(m.error||!m.data){setErr('No customer organization is linked to this account.');return}const o=await supabase.from('organizations').select('id,name,code,status').eq('id',m.data.organization_id).single();setOrg(o.data);const om=await supabase.from('organization_modules').select('module_code').eq('organization_id',m.data.organization_id).eq('enabled',true);setEnabled((om.data||[]).map((x:any)=>x.module_code));const e=await supabase.from('employees').select('employee_code,first_name,last_name,work_email,employment_status,employment_type').eq('organization_id',m.data.organization_id).order('created_at',{ascending:false});setEmp(e.data||[])})()},[])
 async function logout(){await supabase.auth.signOut();location.href='/login'}
 const visible=modules.filter(x=>enabled.includes(x[0]))
 return <main className="app-shell"><aside className="app-side"><img src="/humanest-logo.png" className="side-logo"/><div className="org">{org?.name||'Loading…'}</div><nav><button className={tab==='Dashboard'?'on':''} onClick={()=>setTab('Dashboard')}>Dashboard</button>{visible.map(m=><button key={m[0]} className={tab===m[1]?'on':''} onClick={()=>setTab(m[1])}>{m[1]}</button>)}<button onClick={()=>setTab('My Profile')}>My Profile</button><button onClick={()=>setTab('Settings')}>Settings</button></nav><button className="signout" onClick={logout}>Sign out</button></aside><section className="app-content"><header><div><div className="eyebrow">HUMANEST HRMS</div><h1>{tab}</h1></div><div className="userpill">{user?.email}</div></header>{err?<div className="error">{err}</div>:tab==='Dashboard'?<><div className="welcome"><div><h2>Welcome to HumaNest</h2><p className="muted">Your People. Your Process.</p></div><span className={'status '+(org?.status||'').toLowerCase()}>{org?.status||'...'}</span></div><div className="stats"><div className="stat"><span>Employees</span><b>{emp.length}</b></div><div className="stat"><span>Enabled modules</span><b>{visible.length}</b></div><div className="stat"><span>Organization</span><b>{org?.code||'—'}</b></div><div className="stat"><span>Trial</span><b>{org?.status==='TRIAL'?'7 Day':'Active'}</b></div></div><div className="card"><div className="cardhead"><h2>Employees</h2><button>+ Add Employee</button></div><div className="tablewrap"><table><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Status</th><th>Type</th></tr></thead><tbody>{emp.length?emp.map((e:any)=><tr key={e.employee_code}><td>{e.employee_code}</td><td>{e.first_name} {e.last_name||''}</td><td>{e.work_email}</td><td>{e.employment_status}</td><td>{e.employment_type}</td></tr>):<tr><td colSpan={5} className="empty">No employees yet.</td></tr>}</tbody></table></div></div></>:<div className="card empty-section"><div className="section-icon">✦</div><h2>{tab}</h2><p>This module is enabled for your organization. The production workflow and database operations will be connected in the next implementation stage.</p></div>}</section></main>
}
