'use client'
import {useState} from 'react'
import {supabase} from '../../lib/supabase'
export default function Login(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[factor,setFactor]=useState(''),[mode,setMode]=useState<'login'|'mfa'>('login'),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:any){e.preventDefault();setBusy(true);setErr('');const r=await supabase.auth.signInWithPassword({email,password});if(r.error){setErr(r.error.message);setBusy(false);return}const {data}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(data.currentLevel==='aal2'){location.href='/hrms';return}const f=await supabase.auth.mfa.listFactors();if(f.error){setErr(f.error.message);setBusy(false);return}const verified=(f.data.totp||[]).find((x:any)=>x.status==='verified');if(!verified){setErr('MFA is required. Please enroll an Authenticator factor from the customer security setup.');setBusy(false);return}setFactor(verified.id);setMode('mfa');setBusy(false)}
 async function verify(e:any){e.preventDefault();setBusy(true);setErr('');const c=await supabase.auth.mfa.challenge({factorId:factor});if(c.error){setErr(c.error.message);setBusy(false);return}const v=await supabase.auth.mfa.verify({factorId:factor,challengeId:c.data.challenge.id,code});if(v.error){setErr(v.error.message);setBusy(false);return}location.href='/hrms'}
 return <main className="login-page"><section className="login-brand"><img src="/humanest-logo.png" className="login-logo"/><h1>People Empower<br/>Progress<span>.</span></h1><p>A smarter platform for organizations to manage people, processes and possibilities.</p><div className="mini"><b>People</b><b>Process</b><b>Progress</b></div></section><section className="login-side"><div className="login-card"><img src="/humanest-logo.png" className="card-logo"/><h2>Customer Login</h2>{mode==='login'?<form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{err&&<div className="error">{err}</div>}<button className="gradient" disabled={busy}>{busy?'Signing in…':'Login →'}</button></form>:<form onSubmit={verify}><p className="muted">Enter the 6-digit code from your Authenticator app.</p><input className="code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} maxLength={6} inputMode="numeric" placeholder="000000" required/>{err&&<div className="error">{err}</div>}<button className="gradient" disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify →'}</button></form>}<div className="secure">Secure access · Authenticator MFA</div><a className="back" href="/trial">Create a trial account</a></div></section></main>
}
