'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

const MODULES=[['CORE_HR','Core HR'],['ATTENDANCE','Attendance'],['LEAVE','Leave'],['PAYROLL','Payroll'],['RECRUITMENT','Recruitment'],['ONBOARDING','Onboarding'],['PERFORMANCE','Performance'],['EXPENSES','Expenses'],['REPORTS','Reports']] as const
const TABS=['Overview','Customers','Trials','Modules & Licensing','Platform Users','Audit Log','Settings']
const PLATFORM_ROLES=[['SAAS_ADMIN','SaaS Admin'],['CUSTOMER_SUCCESS','Customer Success'],['SALES','Sales'],['SUPPORT','Support'],['FINANCE','Finance'],['AUDITOR','Auditor'],['SUPER_ADMIN','Super Admin']] as const

type Account=any
export default function PlatformAdmin(){
 const [mode,setMode]=useState<'login'|'setup'|'verify'|'dashboard'>('login'),[user,setUser]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[code,setCode]=useState(''),[factor,setFactor]=useState(''),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('Overview'),[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<Account|null>(null),[modules,setModules]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[platformUsers,setPlatformUsers]=useState<any[]>([]),[refresh,setRefresh]=useState(0)
async function load(){setErr('');const a=await supabase.from('saas_accounts').select('id,organization_id,status,account_type,plan_code,trial_started_at,trial_ends_at,converted_at,disabled_at,notes,trial_employee_quota,user_quota,organizations(id,name,code,status,created_at)').order('created_at',{ascending:false});if(a.error){setErr(a.error.message);return}setAccounts(a.data||[]);const m=await supabase.from('saas_modules').select('module_code,module_name,description,is_active,is_available_for_trial').order('sort_order');if(m.error){setErr(m.error.message);return}setModules(m.data||[]);const al=await supabase.from('saas_admin_audit_logs').select('*').order('created_at',{ascending:false}).limit(100);if(al.error){setErr(al.error.message);return}setAudit(al.data||[]);const {data:{session}}=await supabase.auth.getSession();if(session){const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'list_platform_users'})});const j=await r.json();if(!r.ok){setErr(j.error||'Unable to load platform users')}else setPlatformUsers(j.users||[])}}
 async function startMfa(u:any){const f=await supabase.auth.mfa.listFactors();if(f.error){setErr(f.error.message);return}const verified=(f.data.totp||[]).find((x:any)=>x.status==='verified');if(verified){setFactor(verified.id);setMode('verify');return}const e=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'HumaNest Platform Admin'});if(e.error){setErr(e.error.message);return}setFactor(e.data.id);setQr(e.data.totp?.qr_code||'');setSecret(e.data.totp?.secret||'');setMode('setup')}
 async function submit(e:any){e.preventDefault();setBusy(true);setErr('');const r=await supabase.auth.signInWithPassword({email,password});if(r.error){setErr(r.error.message);setBusy(false);return}setUser(r.data.user);const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.data.currentLevel==='aal2'){setMode('dashboard');await load();setBusy(false);return}await startMfa(r.data.user);setBusy(false)}
 async function verify(){setBusy(true);setErr('');const c=await supabase.auth.mfa.challenge({factorId:factor});if(c.error){setErr(c.error.message);setBusy(false);return}const v=await supabase.auth.mfa.verify({factorId:factor,challengeId:c.data.id,code});if(v.error){setErr(v.error.message);setBusy(false);return}setCode('');setMode('dashboard');await load();setBusy(false)}
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user)return;setUser(data.user);const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.data.currentLevel==='aal2'){setMode('dashboard');load()}else startMfa(data.user)})},[])
 async function action(name:string,payload:any={}){if(!selected)return;setBusy(true);setErr('');const {data:{session}}=await supabase.auth.getSession();const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify({organization_id:selected.organization_id,action:name,...payload})});const j=await r.json();if(!r.ok){setErr(j.error||'Action failed')}else{await load();setSelected((await supabase.from('saas_accounts').select('id,organization_id,status,account_type,plan_code,trial_started_at,trial_ends_at,converted_at,disabled_at,notes,trial_employee_quota,user_quota,organizations(id,name,code,status,created_at)').eq('organization_id',selected.organization_id).single()).data||null)}setBusy(false);setRefresh(x=>x+1)}
 const counts=useMemo(()=>({total:accounts.length,trials:accounts.filter(a=>a.status==='TRIAL').length,active:accounts.filter(a=>a.status==='ACTIVE').length,attention:accounts.filter(a=>['EXPIRED','DISABLED','PENDING_DELETE'].includes(a.status)).length}),[accounts])
 if(mode==='login')return <AuthShell><form onSubmit={submit}><label><span>Email</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label><span>Password</span><div className="password-wrap"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} required/><button type="button" onClick={()=>setShow(!show)}>◉</button></div></label>{err&&<div className="error">{err}</div>}<button className="gradient large" disabled={busy}>{busy?'Signing in…':'Platform Login →'}</button></form></AuthShell>
 if(mode==='setup')return <AuthShell><MfaSetup qr={qr} secret={secret} code={code} setCode={setCode} verify={verify} busy={busy} err={err}/></AuthShell>
 if(mode==='verify')return <AuthShell><div className="mfa-setup"><div className="eyebrow">AUTHENTICATOR MFA</div><h3>Verify Platform Admin</h3><p>Enter the 6-digit code from your registered Authenticator app.</p><input className="code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} maxLength={6} inputMode="numeric" placeholder="000000" autoFocus/>{err&&<div className="error">{err}</div>}<button className="gradient large" onClick={verify} disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify →'}</button></div></AuthShell>
 return <main className="app-shell"><aside className="app-side"><img src="/humanest-logo-tight.png" className="side-logo"/><div className="org">Platform Administration</div><nav>{TABS.map(t=><button key={t} className={tab===t?'on':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><button className="signout" onClick={async()=>{await supabase.auth.signOut();location.href='/platform-admin'}}>Sign out</button></aside><section className="app-content"><header><div><div className="eyebrow left">HUMANEST PLATFORM</div><h1>{tab}</h1></div><div className="userpill">{user?.email}</div></header>{err&&<div className="error top-error">{err}</div>}
 {tab==='Overview'&&<Overview counts={counts} accounts={accounts} onSelect={a=>{setSelected(a);setTab('Customers')}}/>}
 {tab==='Customers'&&<Customers accounts={accounts} selected={selected} setSelected={setSelected} action={action} busy={busy}/>} 
 {tab==='Trials'&&<Trials accounts={accounts} setSelected={a=>{setSelected(a);setTab('Customers')}}/>}
 {tab==='Modules & Licensing'&&<Licensing accounts={accounts} modules={modules} selected={selected} setSelected={setSelected} action={action} busy={busy}/>} 
 {tab==='Platform Users'&&<PlatformUsers rows={platformUsers} onDone={load} setErr={setErr}/>} 
 {tab==='Audit Log'&&<Audit rows={audit}/>} 
 {tab==='Settings'&&<Settings/>}
 </section></main>
}
function Overview({counts,accounts,onSelect}:{counts:any,accounts:any[],onSelect:(a:any)=>void}){return <><div className="stats"><Stat label="Total tenants" value={counts.total}/><Stat label="Trials" value={counts.trials}/><Stat label="Active customers" value={counts.active}/><Stat label="Attention" value={counts.attention}/></div><div className="grid-2"><div className="card"><div className="cardhead"><h2>Recent customers</h2><button onClick={()=>{}}>Refresh</button></div><div className="tablewrap"><table><thead><tr><th>Customer</th><th>Status</th><th>Plan</th><th>Trial end</th><th></th></tr></thead><tbody>{accounts.slice(0,8).map(a=><tr key={a.organization_id}><td><b>{a.organizations?.name}</b><small>{a.organizations?.code}</small></td><td><Badge s={a.status}/></td><td>{a.plan_code}</td><td>{a.trial_ends_at?new Date(a.trial_ends_at).toLocaleDateString():'—'}</td><td><button className="linkbtn" onClick={()=>onSelect(a)}>Manage</button></td></tr>)}{!accounts.length&&<Empty/>}</tbody></table></div></div><div className="card"><h2>Platform controls</h2><div className="control-list"><div><b>Tenant lifecycle</b><span>Create, extend, convert, suspend and delete customer tenants.</span></div><div><b>Module licensing</b><span>Enable or disable modules per customer.</span></div><div><b>Employee licensing</b><span>Set purchased quota and temporary overage.</span></div><div><b>Security</b><span>Authenticator MFA is mandatory for platform administration.</span></div></div></div></div></>}
function Customers({accounts,selected,setSelected,action,busy}:{accounts:any[],selected:any,setSelected:(a:any)=>void,action:any,busy:boolean}){
 const [days,setDays]=useState(7),[quota,setQuota]=useState(25),[userQuota,setUserQuota]=useState(25),[modules,setModules]=useState<string[]>(MODULES.map(x=>x[0]));
 const [detail,setDetail]=useState<any>(null),[admins,setAdmins]=useState<any[]>([]),[adminOpen,setAdminOpen]=useState(false),[adminEdit,setAdminEdit]=useState<any>(null);
 const [adminName,setAdminName]=useState(''),[adminEmail,setAdminEmail]=useState(''),[adminPhone,setAdminPhone]=useState(''),[adminBusy,setAdminBusy]=useState(false);
 async function loadAdmins(){if(!selected)return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'list_customer_admins',organization_id:selected.organization_id})});const j=await r.json();if(!r.ok){setAdmins([]);return}setAdmins(j.users||[])}
 useEffect(()=>{if(!selected)return;setDays(7);setQuota(selected.trial_employee_quota||25);setUserQuota(selected.user_quota||selected.trial_employee_quota||25);supabase.from('organization_modules').select('module_code,enabled').eq('organization_id',selected.organization_id).then(({data})=>setModules((data||[]).filter((x:any)=>x.enabled).map((x:any)=>x.module_code)));loadAdmins()},[selected]);
 useEffect(()=>{if(!selected){setDetail(null);return}Promise.all([supabase.from('organization_members').select('id,user_id,employee_id,status').eq('organization_id',selected.organization_id),supabase.from('employees').select('id').eq('organization_id',selected.organization_id)]).then(([m,e])=>setDetail({members:m.data?.length||0,employees:e.data?.length||0}))},[selected]);
 function openAdmin(a?:any){setAdminEdit(a||null);setAdminName(a?.full_name||'');setAdminEmail(a?.email||'');setAdminPhone(a?.phone||'');setAdminOpen(true)}
 async function saveAdmin(){if(!selected||!adminName.trim()||!adminEmail.trim())return;setAdminBusy(true);const {data:{session}}=await supabase.auth.getSession();if(!session){setAdminBusy(false);return}const act=adminEdit?'update_customer_admin':'create_customer_admin';const payload={action:act,organization_id:selected.organization_id,user_id:adminEdit?.user_id,full_name:adminName.trim(),email:adminEmail.trim().toLowerCase(),phone:adminPhone.trim()};const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){alert(j.error||'Customer admin action failed')}else{setAdminOpen(false);await loadAdmins()}setAdminBusy(false)}
 async function removeAdmin(a:any){if(!confirm(`Delete customer admin ${a.email}? This will remove the account and its linked employee.`))return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'delete_customer_admin',organization_id:selected.organization_id,user_id:a.user_id})});const j=await r.json();if(!r.ok)alert(j.error||'Unable to delete customer admin');else await loadAdmins()}
 return <div className="split"><div className="card"><div className="cardhead"><h2>Customer tenants</h2><span>{accounts.length} tenants</span></div><div className="tenant-list">{accounts.map(a=><button key={a.organization_id} className={selected?.organization_id===a.organization_id?'tenant on':'tenant'} onClick={()=>setSelected(a)}><span><b>{a.organizations?.name}</b><small>{a.organizations?.code}</small></span><Badge s={a.status}/></button>)}</div></div>{selected?<div className="card detail"><div className="detail-head"><div><h2>{selected.organizations?.name}</h2><p>{selected.organizations?.code} · Created {new Date(selected.organizations?.created_at).toLocaleDateString()}</p></div><Badge s={selected.status}/></div><div className="stats mini"><Stat label="Employees" value={detail?.employees??'…'}/><Stat label="Users" value={detail?.members??'…'}/><Stat label="Employee quota" value={selected.trial_employee_quota}/><Stat label="User quota" value={selected.user_quota}/><Stat label="Trial ends" value={selected.trial_ends_at?new Date(selected.trial_ends_at).toLocaleDateString():'—'}/></div><div className="action-row"><button onClick={()=>action('extend_trial',{trial_days:days})} disabled={busy}>Extend trial</button><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select><button onClick={()=>action(selected.status==='DISABLED'?'enable':'disable')} disabled={busy}>{selected.status==='DISABLED'?'Enable tenant':'Suspend tenant'}</button><button className="danger" onClick={()=>{if(confirm('Delete this tenant and all customer users? This cannot be undone.'))action('delete')}} disabled={busy}>Delete Tenant</button></div>
 <div className="card inset"><div className="cardhead"><div><h3>Customer administrators</h3><p className="muted">View, add, edit or remove customer admin accounts.</p></div><button className="gradient" onClick={()=>openAdmin()}>+ Add Customer Admin</button></div>{adminOpen&&<div className="form-grid"><label><span>Full name</span><input value={adminName} onChange={e=>setAdminName(e.target.value)}/></label><label><span>Email</span><input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} /></label><label><span>Contact number</span><input value={adminPhone} onChange={e=>setAdminPhone(e.target.value)} placeholder="+91..."/></label><div className="action-row"><button onClick={()=>setAdminOpen(false)}>Cancel</button><button className="gradient" onClick={saveAdmin} disabled={adminBusy||!adminName||!adminEmail}>{adminBusy?'Saving…':adminEdit?'Save changes':'Create & Send Invitation'}</button></div></div>}<div className="tablewrap"><table><thead><tr><th>Administrator</th><th>Email</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody>{admins.map(a=><tr key={a.user_id}><td>{a.full_name||'—'}</td><td>{a.email}</td><td>{a.phone||'—'}</td><td><Badge s={a.status}/></td><td><button onClick={()=>openAdmin(a)}>Edit</button> <button className="danger" onClick={()=>removeAdmin(a)}>Delete</button></td></tr>)}{!admins.length&&<Empty/>}</tbody></table></div></div>
 <div className="card inset"><h3>Licensing</h3><div className="inline-form"><label><span>Employees</span><input type="number" min={1} value={quota} onChange={e=>setQuota(Number(e.target.value))}/></label><label><span>Users</span><input type="number" min={1} value={userQuota} onChange={e=>setUserQuota(Number(e.target.value))}/></label><button onClick={()=>action('set_license',{employee_quota:quota,user_quota:userQuota,overage_quota:0})} disabled={busy}>Save quota</button></div><p className="muted">Hard limits applied to the customer workspace.</p></div><div className="card inset"><h3>Module customization</h3><div className="check-grid">{MODULES.map(([code,name])=><label key={code} className="check"><input type="checkbox" checked={modules.includes(code)} onChange={e=>setModules(x=>e.target.checked?[...new Set([...x,code])]:x.filter(v=>v!==code))}/><span>{name}</span></label>)}</div><button className="gradient" onClick={()=>action('set_modules',{modules})} disabled={busy}>Save module configuration</button></div><div className="card inset"><h3>Convert to Active Customer</h3><p className="muted">Converts the trial to an ACTIVE customer and applies the selected modules.</p><button className="gradient" onClick={()=>action('convert',{plan_code:'CUSTOM',modules})} disabled={busy}>Convert to Active Customer</button></div></div>:<div className="card empty-section"><h2>Select a customer</h2><p>Choose a tenant to manage trial, modules, licensing, administrators and lifecycle.</p></div>}</div>}
function Trials({accounts,setSelected}:{accounts:any[],setSelected:(a:any)=>void}){const rows=accounts.filter(a=>['TRIAL','EXPIRED'].includes(a.status));return <div className="card"><div className="cardhead"><h2>Trial management</h2><span>{rows.length} trial accounts</span></div><table><thead><tr><th>Customer</th><th>Status</th><th>Started</th><th>Ends</th><th>Employee quota</th><th></th></tr></thead><tbody>{rows.map(a=><tr key={a.organization_id}><td><b>{a.organizations?.name}</b><small>{a.organizations?.code}</small></td><td><Badge s={a.status}/></td><td>{a.trial_started_at?new Date(a.trial_started_at).toLocaleDateString():'—'}</td><td>{a.trial_ends_at?new Date(a.trial_ends_at).toLocaleString():'—'}</td><td>{a.trial_employee_quota}</td><td><button className="linkbtn" onClick={()=>setSelected(a)}>Manage</button></td></tr>)}{!rows.length&&<Empty/>}</tbody></table></div>}
function Licensing({accounts,modules,selected,setSelected,action,busy}:{accounts:any[],modules:any[],selected:any,setSelected:(a:any)=>void,action:any,busy:boolean}){return <div className="grid-2"><div className="card"><h2>Module catalog</h2><div className="catalog">{modules.map(m=><div className="catalog-row" key={m.module_code}><div><b>{m.module_name||m.module_code}</b><span>{m.description||'HumaNest module'}</span></div><Badge s={m.is_active?'ACTIVE':'DISABLED'}/></div>)}</div></div><div className="card"><h2>Customer licensing</h2><table><thead><tr><th>Customer</th><th>Plan</th><th>Quota</th><th>Status</th><th></th></tr></thead><tbody>{accounts.map(a=><tr key={a.organization_id}><td>{a.organizations?.name}</td><td>{a.plan_code}</td><td>{a.trial_employee_quota}</td><td><Badge s={a.status}/></td><td><button className="linkbtn" onClick={()=>setSelected(a)}>Manage</button></td></tr>)}</tbody></table></div></div>}
function PlatformUsers({rows,onDone,setErr}:{rows:any[],onDone:()=>Promise<void>,setErr:(x:string)=>void}){const [open,setOpen]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[role,setRole]=useState('SAAS_ADMIN'),[busy,setBusy]=useState(false);async function call(action:string,payload:any={}){setBusy(true);setErr('');const {data:{session}}=await supabase.auth.getSession();if(!session){setErr('Session expired');setBusy(false);return}const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/trial-provision`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!r.ok)setErr(j.error||'Action failed');else{setOpen(false);setName('');setEmail('');setPhone('');setRole('SAAS_ADMIN');await onDone()}setBusy(false)}return <div className='card'><div className='cardhead'><div><h2>Platform users</h2><span>{rows.length} users</span></div><button className='gradient' onClick={()=>setOpen(true)}>+ Create Platform User</button></div>{open&&<div className='card inset'><h3>Create platform user</h3><p className='muted'>The user will receive an invitation email and must complete Authenticator MFA before using platform administration.</p><div className='form-grid'><label><span>Full name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder='Full name'/></label><label><span>Email</span><input type='email' value={email} onChange={e=>setEmail(e.target.value)} placeholder='name@humanest.co.in'/></label><label><span>Phone</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder='+91'/></label><label><span>Platform role</span><select value={role} onChange={e=>setRole(e.target.value)}>{PLATFORM_ROLES.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label></div><div className='action-row'><button onClick={()=>setOpen(false)}>Cancel</button><button className='gradient' disabled={busy||!name||!email} onClick={()=>call('create_platform_user',{full_name:name,email,phone,role_code:role})}>{busy?'Creating…':'Create & Send Invitation'}</button></div></div>}<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Access</th><th>Action</th></tr></thead><tbody>{rows.map(r=><PlatformUserRow key={r.id} row={r} call={call} busy={busy}/>)}{!rows.length&&<Empty/>}</tbody></table></div>}
function PlatformUserRow({row,call,busy}:{row:any,call:(a:string,p?:any)=>Promise<void>,busy:boolean}){const [role,setRole]=useState(row.role_code||'SAAS_ADMIN');const [edit,setEdit]=useState(false);return <tr><td><b>{row.full_name||'Unnamed'}</b><small>{row.phone||''}</small></td><td>{row.email}</td><td>{edit?<select value={role} onChange={e=>setRole(e.target.value)}>{PLATFORM_ROLES.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select>:row.role_name||'—'}</td><td><Badge s={row.status}/></td><td>{row.is_platform_admin?'Super Admin':'Authenticator MFA required'}</td><td><div className='action-row'>{edit?<><button onClick={()=>{call('set_platform_role',{user_id:row.id,role_code:role});setEdit(false)}} disabled={busy}>Save role</button><button onClick={()=>setEdit(false)}>Cancel</button></>:<button onClick={()=>setEdit(true)}>Change role</button>}{row.status==='DISABLED'?<button onClick={()=>call('enable_platform_user',{user_id:row.id})} disabled={busy}>Enable</button>:<button className='danger' onClick={()=>{if(confirm(`Disable ${row.email}?`))call('disable_platform_user',{user_id:row.id})}} disabled={busy}>Disable</button>}</div></td></tr>}
function Audit({rows}:{rows:any[]}){return <div className="card"><div className="cardhead"><h2>Audit log</h2><span>{rows.length} recent events</span></div><table><thead><tr><th>Time</th><th>Action</th><th>Organization</th><th>Details</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td><Badge s={r.action}/></td><td>{r.organization_id||'—'}</td><td><code>{JSON.stringify(r.details||{})}</code></td></tr>)}{!rows.length&&<Empty/>}</tbody></table></div>}
function Settings(){return <div className="grid-2"><div className="card"><h2>Platform defaults</h2><div className="setting"><span>Default free trial</span><b>7 days</b></div><div className="setting"><span>Trial employee quota</span><b>25 employees</b></div><div className="setting"><span>Customer MFA</span><b>Mandatory TOTP</b></div><div className="setting"><span>Default currency</span><b>INR</b></div></div><div className="card"><h2>Go-live controls</h2><div className="control-list"><div><b>Tenant isolation</b><span>RLS enforced per organization.</span></div><div><b>Platform MFA</b><span>Authenticator MFA required.</span></div><div><b>Trial expiry</b><span>Hourly expiry job configured.</span></div><div><b>Audit</b><span>Platform lifecycle actions are recorded.</span></div></div></div></div>}
function Stat({label,value}:{label:string,value:any}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
function Badge({s}:{s:string}){return <span className={'badge '+String(s||'').toLowerCase().replaceAll(' ','-')}>{s}</span>}
function Empty(){return <tr><td colSpan={10} className="empty">No records found.</td></tr>}
function MfaSetup({qr,secret,code,setCode,verify,busy,err}:{qr:string,secret:string,code:string,setCode:any,verify:any,busy:boolean,err:string}){return <div className="mfa-setup"><div className="eyebrow">FIRST-TIME SECURITY SETUP</div><h3>Set up Authenticator MFA</h3><p>Scan the QR code with Microsoft Authenticator, Google Authenticator, Authy or another TOTP app.</p>{qr&&<div className="qr-box"><img src={qr.startsWith('data:')?qr:`data:image/svg+xml;utf8,${encodeURIComponent(qr)}`} alt="Authenticator QR"/></div>}<div className="secret-box"><small>Manual setup key</small><b>{secret}</b></div><input className="code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} maxLength={6} inputMode="numeric" placeholder="000000"/>{err&&<div className="error">{err}</div>}<button className="gradient large" onClick={verify} disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify & Activate MFA →'}</button></div>}
function AuthShell({children}:{children:any}){return <main className="auth-page platform-auth"><div className="auth-topline">A BRIGHTER TOMORROW TOGETHER</div><section className="auth-brand"><a href="/" className="back-home">← Back to Home</a><div className="brand-center"><img src="/humanest-logo-tight.png" className="auth-logo"/><h1>People Empower<br/>Progress<span>.</span></h1><p>A smarter platform for organizations<br/>to manage people, processes and possibilities.</p></div><div className="auth-wave"/></section><section className="auth-form-area"><div className="glass-card"><img src="/humanest-logo-tight.png" className="form-logo"/><h2>Platform Login</h2><p className="subtitle">Customers · Licensing · Trials · Platform Operations</p>{children}<div className="secure-note">Protected with Authenticator MFA</div></div></section></main>}
