'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
const tabs=['Overview','Customers','Modules & Licensing','Trials','Platform Users','Audit Log','Settings']
export default function PlatformAdmin(){
 const [user,setUser]=useState<any>(null),[tab,setTab]=useState('Overview'),[accounts,setAccounts]=useState<any[]>([]),[mfa,setMfa]=useState(false),[code,setCode]=useState(''),[factor,setFactor]=useState(''),[err,setErr]=useState('')
 async function boot(){const u=await supabase.auth.getUser();if(!u.data.user)return;setUser(u.data.user);const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.data.currentLevel!=='aal2'){const f=await supabase.auth.mfa.listFactors();const v=(f.data?.totp||[]).find((x:any)=>x.status==='verified');if(v){setFactor(v.id);setMfa(true);return}else{const e=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'HumaNest Platform Admin'});if(e.error){setErr(e.error.message);return}setFactor(e.data.id);setMfa(true)}}else load()}
 async function load(){const r=await supabase.from('saas_accounts').select('organization_id,status,account_type,plan_code,trial_ends_at,organizations(name,code)').order('created_at',{ascending:false});if(r.error)setErr(r.error.message);else setAccounts(r.data||[])}
 useEffect(()=>{boot()},[])
 async function verify(){const c=await supabase.auth.mfa.challenge({factorId:factor});if(c.error){setErr(c.error.message);return}const v=await supabase.auth.mfa.verify({factorId:factor,challengeId:c.data.challenge.id,code});if(v.error){setErr(v.error.message);return}setMfa(false);load()}
 async function logout(){await supabase.auth.signOut();location.href='/platform-admin'}
 if(!user)return <main className="mfa-login"><div className="login-card"><img src="/humanest-logo.png" className="card-logo"/><h2>Platform Admin</h2><p className="muted">Sign in using your HumaNest administrator account.</p><a className="gradient block" href="/login">Open Platform Login</a></div></main>
 if(mfa)return <main className="mfa-login"><div className="login-card"><img src="/humanest-logo.png" className="card-logo"/><div className="eyebrow">AUTHENTICATOR MFA</div><h2>Verify Platform Admin</h2><p className="muted">Enter the 6-digit code from your authenticator app.</p><input className="code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/>{err&&<div className="error">{err}</div>}<button className="gradient" onClick={verify} disabled={code.length!==6}>Verify →</button></div></main>
 const count=(s:string)=>accounts.filter(x=>x.status===s).length
 return <main className="app-shell"><aside className="app-side"><img src="/humanest-logo.png" className="side-logo"/><div className="org">Platform Admin</div><nav>{tabs.map(t=><button key={t} className={tab===t?'on':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><button className="signout" onClick={logout}>Sign out</button></aside><section className="app-content"><header><div><div className="eyebrow">HUMANEST PLATFORM</div><h1>{tab}</h1></div><div className="userpill">{user.email}</div></header>{tab==='Overview'?<><div className="stats"><div className="stat"><span>Total tenants</span><b>{accounts.length}</b></div><div className="stat"><span>Trials</span><b>{count('TRIAL')}</b></div><div className="stat"><span>Active</span><b>{count('ACTIVE')}</b></div><div className="stat"><span>Attention</span><b>{accounts.filter(x=>['EXPIRED','DISABLED','PENDING_DELETE'].includes(x.status)).length}</b></div></div><div className="card"><div className="cardhead"><h2>Customer tenants</h2><button onClick={()=>setTab('Customers')}>Manage Customers →</button></div><div className="tablewrap"><table><thead><tr><th>Customer</th><th>Status</th><th>Plan</th><th>Trial ends</th></tr></thead><tbody>{accounts.length?accounts.map(a=><tr key={a.organization_id}><td><b>{a.organizations?.name||'Unnamed'}</b><small>{a.organizations?.code}</small></td><td><span className={'badge '+a.status.toLowerCase()}>{a.status}</span></td><td>{a.plan_code}</td><td>{a.trial_ends_at?new Date(a.trial_ends_at).toLocaleDateString():'—'}</td></tr>):<tr><td colSpan={4} className="empty">No customer tenants yet. Use Create Trial on the public page to create one.</td></tr>}</tbody></table></div></div></>:<div className="card empty-section"><div className="section-icon">◆</div><h2>{tab}</h2><p>Section is clickable and ready for the next live database workflow.</p>{tab==='Customers'&&<a className="gradient inline" href="/trial">Create a 7-Day Trial →</a>}</div>}</section></main>
}
